### PR TITLE
WIP Update all examples to fresh forks.

### PR DESCRIPTION
**Pull request by curran**
In preparation for releasing 1.0 (#37) and updating all examples (#52), I forked all the bl.ocks.org-based examples and updated the links here, so that 1.0 can be released and the README will not need to change after that point. After releasing 1.0, I plan to go through and upgrade all the examples to use it.

Also, replaced broken https://bl.ocks.org/mbostock/5593150 with https://beta.observablehq.com/@mbostock/d3-vector-tiles , as suggested by @Fil  in #37.

After releasing 1.0, looking forward to try Observable's Suggestion feature for upgrading that one!

### CODE REVIEW

**Comment by curran** [comment]
Remaining task here: make sure all thumbnails are working.

**Comment by mbostock** [comment]
Good catch! I moved that example over to the D3 organization on Observable and added a redirect from the broken block.

https://observablehq.com/@d3/vector-tiles

**Comment by mbostock** [comment]
I have been working on new examples and documentation here:

https://observablehq.com/collection/@d3/d3-tile

I’m still using the 0.0.3 API because the *tx* and *ty* introduced by 0.0.4 feel pretty awkward. All of the examples I could find rely on a stringify function that is applied as a transform to the container element, which often isn’t what I want.

```js
function stringify(scale, translate) {
  var k = scale / 256, r = scale % 1 ? Number : Math.round;
  return "translate(" + r(translate[0] * scale) + "," + r(translate[1] * scale) + ") scale(" + k + ")";
}
```

And furthermore that stringify function assumes as tile size of 256 (I think), so it won’t work with other tile sizes.

I’d like to think over the API design before we release 1.0.

**Comment by mbostock** [comment]
Closing this PR as the examples and documentation will live on Observable. Let me know if you’d like an invite to the D3 team there to help out.

**Pull request closed without merging**
