### PR TITLE
Adding to tile.tileSize

### PR DESCRIPTION
**Pull request by linusmarco**
I added a tileSize method to address issue #22 (with test and updated README).

An example using the updated code is here:
http://bl.ocks.org/linusmarco/71f80d7c8a53981f5bbfab8167f32a10

### CODE REVIEW

**Comment by linusmarco** [comment]
Ah, good catch! I was not aware of that compatibility issue. Although based on the table you posted, it looks like log10 is not supported in IE11 either. We can use natural logs, though (I'm assuming that's probably what you meant anyway). I can change the two instances of 
`Math.log2(tileSize)` 
to 
`Math.log(tileSize) / Math.log(2)`
or better yet, move that calculation to a constant so that it doesn't need to be repeated.

I'll give Mike a chance to weigh in first, though.

**Comment by curran** [comment]
Yes, sorry, I meant `Math.log`, which is widely supported.

Please feel free to make the change and optimize/refactor as you see fit. If @mbostock doesn't weigh in, I can go ahead and merge this and cut a release. This code has sat undisturbed for some time, I feel like we could cut a 1.0 after this change.

**Comment by linusmarco** [comment]
Made the change--should be all set to merge. 

I agree that everything seems complete enough to move to 1.0. I've been using the module on several projects for a while and haven't run into any issues. Thanks to you guys for developing this!

**Comment by curran** [comment]
Great to hear! I agree. Thank you so much for this work.

**Pull request merged**
